db:
  image: postgres
  ports:
    - "2000:5432"
  volumes:
    - siorb-postgres:/var/lib/postgresql/data
redis:
  image: redis
  volumes:
    - siorb-postgres:/var/lib/postgresql/data
web:
  build: .
  command: bash -c "service nginx start & bundle exec puma -e production -p 3000"
  volumes:
    - .:/app
  ports:
    - "81:80"
  links:
    - db
    - redis
  env_file:
    - .env
worker:
  build: .
  command: bundle exec sidekiq -e production -c 2
  links:
    - db
    - redis
  env_file:
    - .env

