db:
  image: postgres
  ports:
   - "2000:5432"
  volumes:
    - siorb-postgres:/var/lib/postgresql/data
redis:
  image: redis
  volumes:
    - siorb-postgres:/var/lib/postgresql/data
web:
  build: .
  command: bundle exec puma -p 3000
  volumes:
    - .:/app
  ports:
    - "80:3000"
  links:
    - db
    - redis
  env_file:
    - .env
worker:
  build: .
  command: bundle exec sidekiq -e production -c 2
  links:
    - db
    - redis
  env_file:
    - .env

